### ISSUE TITLE
LimPIDFreeze in WECC only freezes integrator

### ISSUE THREAD

**Issue by martinscripts** [bertrtam00/wecc_iec_model_comparison#1]
LimPIDFreeze in WECC only freezes integrator;
documentation seems like it should freeze whole PI controller. 

![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/33164d9d-a07f-4511-8461-00f602446f8f)

**Comment by adriguir** [comment]
@bertrtam00 could you have a look to what is done in the PowerFactory implementation? Do they also freeze the P part?

**Comment by martinscripts** [comment]
@adriguir no actually they also only freeze the integral part: 
(the red proportional part isnt frozen here and the blue part is the integral one -- it gets frozen above, not shown here)
![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/976d0f67-d883-41a0-a459-dd8c58768fc0)

Now that I look at the WECC documentation again I would say that it might be intended that way.
![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/aefe78df-e2b5-4d7d-9ef3-a97b2c82edbb)
It says "Freeze State", not "output of controller". So probably that's equivalent to the IEC freezing.
