### ISSUE TITLE
implement REGC_A into full model

### ISSUE THREAD

**Issue by martinscripts** [bertrtam00/wecc_iec_model_comparison#16]

**Comment by martinscripts** [comment]
- command is now following setpoint with a delay, as expected.
![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/05971aa3-43a9-4d90-a838-a95b2c5b3b64)

**Comment by martinscripts** [comment]
@adriguir 
these parameters are defined in LowVoltagePowerLogic and REGC_A but should be defined in the mask of  REGC_A or even in the mask of WECC_WT4B.
Could you find out how to do that?

![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/7d7d8404-7397-48d7-86f2-70620c3a9e18)
![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/e33bafa9-7198-41f1-8f88-25383e8b6107)

**Comment by adriguir** [comment]
Solved by the aforementioned PR. 
The point is that you need to "get the parameters down to the block where you use them". So if you want to be able to set them at the upper level, then you need to have some zerox = zerox to go from the upper level to the final LVPL for example
