### ISSUE TITLE
WECC doesnt initialize like IEC

### ISSUE THREAD

**Issue by martinscripts** [bertrtam00/wecc_iec_model_comparison#2]
- Mode = 1 (Q control)

WECC doesn't initialize in steady state like IEC.
Integrator initial value starts at 0.5, defined here:
![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/56085b2b-3331-4e44-b1c3-eb1e5b423363)
![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/f3a6ba6f-7933-46ed-a979-b3e44bd8ae6a)

Here a the plot.
![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/ffc04dcc-912f-449b-95e4-74ade777eac7)

Also with Y0=1 in the Q-controller integrator it does not initialize properly. 
see here: 
![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/e2626dcf-5deb-41a9-a970-622b834337a0)

**Comment by adriguir** [comment]
The initialization value of the integrator should be UInj0Pu / Kqp.
Indeed you want to have UInj0Pu as the output of the LimPIDFreeze block, it implies (going backward) that the output of the integrator is UInj0Pu / Kqp
