### ISSUE TITLE
test004_UStep find differences

### ISSUE THREAD

**Issue by martinscripts** [bertrtam00/wecc_iec_model_comparison#26]
Doing step from 1 to 1.1 p.u.

first had to increase x of lines to x=10 in system base (x_base100), equivalent to x_base1 = 0.1

**Comment by martinscripts** [comment]
WECC reacts in wrong direction?

![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/1309193f-ec0f-48f5-8fd7-f7896cc3f421)

**Comment by martinscripts** [comment]
There is an (I would say) error in the Q control path of WECC implementation:

![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/c106b1fc-10f2-47be-96ff-e80870948125)

compared to docs:
![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/9ede0e3a-7aa7-4d33-8566-6e49bad6e33a)

This is only apparent when in U mode, not in Q mode, because this path is not active in Q mode.

**Comment by martinscripts** [comment]
For a larger u step (+0.1 p.u.)
WECC works fine
but IEC goes into some limit:
![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/a84a6e9e-7d6a-47b5-b288-1b0e1c9bfa36)

## It's the CLS
![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/596e9dcf-3602-4d70-9bda-79697162f697)
- with rising voltage, IqMinPu gets narrower 
-  prevents voltage from getting too high, which is expected behaviour

**Comment by martinscripts** [comment]
It was the Kpqu Path as documented in the comparison report in section 6.1.1.

**But I was wrong about the sign convention there** (already corrected in latest report version now)
![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/c8dbaa7d-29c5-49d3-94ca-9ab0f610b4b0)

- now speaking in our common sign convention: Kpqu regulates how much iqmin is narrowed towards zero in case of overvoltage
- this prevents more +Q in case of U> to prevent even more overvoltage
- This can be disabled by setting Kpqu to a very high value, e.g. Kpqu=1e12

![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/8dba0564-b65d-4994-8e8b-be1a15782224)

![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/0b68af5a-bb62-4bac-89d7-b2a3cd1c5dd1)

**Comment by martinscripts** [comment]
now same behaviour has been obtained

**Comment by adriguir** [comment]
I thought doing U step should be easy as Q step were matching but you were right in double checking it and finally there were some bad surprises... hopefully you solved them :)

**Comment by martinscripts** [comment]
yes, it works now :) 
And there differences in QStep that aren't explained yet, have a look at #25
