### ISSUE TITLE
Add automatic launching through mos scripts

### ISSUE THREAD

**Issue by adriguir** [bertrtam00/wecc_iec_model_comparison#27]
It will help industrialize or automatize the calculations.
I will add an example working at least in my Windows to be updated then, depening on everyone's installation.

**Comment by martinscripts** [comment]
I tried and don't get any results.

after putting my project path into the .mos file
and typing 
![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/a3663aaa-f3ed-4f01-804f-45f8d7ee50d4)

This window opens for a second
![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/f87cb2b6-113d-4b4e-b1a7-857556b2cea9)

and I cannot find any results

**Comment by martinscripts** [comment]
solved with adrien. This works:

FILE := "T1";
OUT_PATH := "D:/User/mfranke/documents/projects/RTE\simulation_results/T1";
VARIABLES := "(.*line\\_(WECC|IEC)\\.(P1Pu|Q1Pu))|(pWTrefPu\\.y)|(xWTrefPu\\.y)";

PROJECT_HOME := "D:/User/mfranke/documents/projects/RTE/modelica"; // To be adapted! Please keep in mind that even in Windows, you should have the path written in a Linux fashion, using / and not \
STOP_TIME := 10;

loadFile(PROJECT_HOME + "/Dynawo/package.mo"); getErrorString();

loadFile(PROJECT_HOME + "/test_cases/" + FILE + ".mo"); getErrorString();

setCommandLineOptions("--matchingAlgorithm=PFPlusExt --indexReductionMethod=dynamicStateSelection -d=initialization,NLSanalyticJacobian,newInst -d=initialization"); getErrorString();
buildModel(T1, outputFormat="csv", variableFilter=VARIABLES, stopTime=STOP_TIME); getErrorString();

//
//ADAPT NAME HERE AS WELL
//      |
//      v
system("T1.exe -noEventEmit -r="+ OUT_PATH +"/"+ FILE + "_res.csv");


// system("del *.o *.c *.log *.h *.exe *.libs *.makefile *.json *.xml *.intdata *.realdata");
