### ISSUE TITLE
uFiltPu in WECC not working if line B=0 and G=0

### ISSUE THREAD

**Issue by martinscripts** [bertrtam00/wecc_iec_model_comparison#3]
If conductance and susceptance of line_WECC are G=0 and B=0, then the voltage drop isn't measured (uFilteredPu) anymore.

# comparison plots
## With G=B=1e-12
![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/aedf7d39-e304-4422-98b5-b6454a879345)
## With G=B=0
![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/e8095832-b7cb-496c-b448-cae1d2ef5821)

# Terminals voltages of line_WECC
at terminal1 there is no voltage change;
at terminal 2 there is.
(for line_IEC the voltage drop is visible at both terminals)
![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/eff1cc7a-bc8f-44c3-8322-e1a6a8eb908c)

**Comment by martinscripts** [comment]
Tried the following now: 

- remove and reconnect terminal connections
- delete and re-instantiate line_WECC model
- delete and re-instantiate bus_WECC model
- give WECC model own setpoint inputs instead of using common ones for IEC and WECC models

![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/3fc4f6bb-3e0d-4f88-89cd-125c9fd2c1e7)

With each change the uFilt of WECC model changes in a seemingly unpredictable way. 
line_WECC.terminal1.V doent show the voltage step. terminal2.V is fine.

![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/55b0ddc9-2d9e-4ebf-99fc-9e9839a2074b)

**Comment by martinscripts** [comment]
The reason seems to be that the voltage drop from the bus_WECC doesnt get propagated to the line_WECC.terminal1

Can this be related to the warning 
Homotopy solver total pivot: Matrix (nearly) singular at time [...] ?

**Comment by adriguir** [comment]
It seems to be linked to the implementation of the internal line in the WECC model. 
When having RPu = 0 and XPu = 0 in this line plus small values in the outside line, it seems to cause some troubles (certainly numerical problems) and we can't have confidence in the solution being found. In the IEC model in the converter the line is not explicitly modeled using a line model but with the eqations being written in a slightly different way and that seems to work better.
Once we go to more natural values of X (for example X = 0.1 pu), WECC model works fine.
Another way of having it working fine is to delete the internal line when RPu = XPu = 0. By doing that, the model works as expected also with very small values like X = 2e-6 on the external line. 

Thus I would recommend leaving this problem aside and going on with the rest (if needed @bertrtam00 I can push the modifications to get rid of the internal line in the WECC model)

**Comment by martinscripts** [comment]
thanks for your investigation. No need to push, I think. If needed I can delete the internal line model.


Changed internal reactance to XesPu = 0.01 p.u. (and XPu=0.01 for WECC model)

![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/b77ed5d6-1381-43b3-b69b-b92c766a252a)

**Comment by martinscripts** [comment]
maybe it makes sense to re-implement this like in the IEC model?

**Comment by martinscripts** [comment]
close for now
