### ISSUE TITLE
Implement REGC_A in its correct form

### ISSUE THREAD

**Issue by adriguir** [bertrtam00/wecc_iec_model_comparison#7]

**Comment by martinscripts** [comment]
# existing REGC
@adriguir 
can someone explain the logic of the marked area in the following image?

![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/9076540e-2784-495b-8bd3-bb30f7419f2f)

I am expecting something like this 
![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/26382201/3c0cb583-deeb-4788-9f64-1f7eb71ce513)
but it doesn't seem to be quite that.

**Comment by adriguir** [comment]
I don't really know nor remember why it was implemented this way but the current behavior is that the limits are only applied during a certain time (=max(abs(1/iqrMin), abs(1/iqrMax)) at the clearing of the fault. Then it is released.
Here is a screenshot of the behavior for iqrMin = -100 and iqrMax = 100 (default parameters of the test case):

![image](https://github.com/bertrtam00/wecc_iec_model_comparison/assets/38657764/5e454a27-5398-4a80-a670-6957aff3fc22)

The limits are then applied from t = 6 to t = 6.01 s. 

I don't know what one should understand for the sentence "rate limits on reactive current for recovery after fault". I understand that the implementation has be done that the behavior and the limits are really transient after the fault and don't last for the remaining part of the simulation

**Comment by martinscripts** [comment]
> "rate limits on reactive current for recovery after fault". I understand that the implementation has be done that the behavior and the limits are really transient after the fault and don't last for the remaining part of the simulation

- I understood this more as a hint on what this limit is for. (not certain, though. I will have a look at PowerFactory implementation)
- there is a remark that the pos. limit only shall beactive for pos. Qgen0 and vice versa for negative limits.

**Comment by martinscripts** [comment]
- In PowerFactory the implementation is done like I assumed
  - positive ramp rate limit active if Qgen0 > 0
  - negative amp rate limit active if Qgen0 < 0
  - no time limits, no FRT signal used in calculation
